### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [KhrystynaKo/Kinozal#2]
нет скруглений
![image](https://user-images.githubusercontent.com/8464662/69670327-58dc5a00-109c-11ea-8577-9110e4e5c816.png)

горизонтальный скрол
![image](https://user-images.githubusercontent.com/8464662/69670362-6bef2a00-109c-11ea-8d4e-a5e6f44f8260.png)

невалидный код
![image](https://user-images.githubusercontent.com/8464662/69670507-c092a500-109c-11ea-986b-aa528e99227a.png)

**Comment by KhrystynaKo** [comment]
Доброе утро! поправила)

**Comment by KhrystynaKo** [comment]
https://khrystynako.github.io/Kinozal/
https://github.com/KhrystynaKo/Kinozal

**Comment by Alecto** [comment]
![image](https://user-images.githubusercontent.com/8464662/69830969-f2884080-122f-11ea-87d0-d1eb9128abd0.png)

разрывается.
![image](https://user-images.githubusercontent.com/8464662/69830978-05027a00-1230-11ea-8c6e-03ecb11e2f7c.png)

**Comment by Alecto** [comment]
там же, добавил

ср, 27 лист. 2019 о 11:07 KhrystynaKo <notifications@github.com> пише:

**Comment by KhrystynaKo** [comment]
Добрый вечер! поправила

**Comment by Alecto** [comment]
не исправлено
![image](https://user-images.githubusercontent.com/8464662/69986897-fcb78100-1546-11ea-8b62-e0f6cffe3513.png)

**Comment by KhrystynaKo** [comment]
добрый день! полосы переделала, а вот блок под видео я, видимо не понимаю, как нужно исправить, так как в папке с примерами нет образца для маленьких разрешений, а в Вашем примере все так же разрывается, как было у меня изначально. Поэтому я переделала снова, но на свой лад.

**Comment by Alecto** [comment]
значит плохой у меня пример.а вам - исправить, чтобы бэйдж не отрывался от текста.
не исправлено.
![image](https://user-images.githubusercontent.com/8464662/70346812-d6a42080-1867-11ea-8ae7-67a6af9838de.png)

**Comment by KhrystynaKo** [comment]
Добрый вечер! сделала, чтобы текст переносился при уменьшении, но бейджи при этом не отрывались от текста

**Comment by Alecto** [comment]
как видите, ничего сложного )
работа принята.

сб, 7 груд. 2019 о 21:18 KhrystynaKo <notifications@github.com> пише:
